Miscellaneous fixes
QubesOS/qubes-app-linux-split-gpg pull request #50
Opened 2021-09-11 21:45 UTC by DemiMarie

This is miscellaneous fixes that were easy to implement.

2021-10-01 10:35 UTC, marmarek commented
This appears to break several things. Unfortunately automatic test result collection didn't work (unrelated openQA issue), so here is the full log: https://openqa.qubes-os.org/tests/23199/file/system_tests-tests-qubes.tests.extra.log

Example failures:
```
=====================================================================
FAIL: splitgpg.tests/TC_00_Direct_debian-11/test_080_option_parser
Check if split-gpg agrees with gpg about options parsing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 367, in test_080_option_parser
    splitgpg_needs_arg = self._check_if_options_takes_argument(
  File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 348, in _check_if_options_takes_argument
    self.fail(
AssertionError: qubes-gpg-client --list-key have not complained about --garbage options: Abbreviated option ‘--list-key’ must be written as ‘--list-keys’


======================================================================
FAIL: splitgpg.tests/TC_00_Direct_fedora-34/test_031_sign_verify_detached
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 161, in test_031_sign_verify_detached
    self.assertIn('\ngpg: Good signature from', verification_result.decode())
AssertionError: '\ngpg: Good signature from' not found in "IDs must not start with '-'\nEOF\n"

======================================================================
FAIL: splitgpg.tests/TC_00_Direct_fedora-34/test_050_sign_verify_files
Test for --output option
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 269, in test_050_sign_verify_files
    self.assertEquals(decoded_msg.decode(), msg)
AssertionError: '' != 'Test message'
+ Test message
```

The first one is because `--list-key` is a valid alias for the `--list-keys` option, not only abbreviation.

2021-10-01 13:40 UTC, DemiMarie commented
> This appears to break several things. Unfortunately automatic test result collection didn't work (unrelated openQA issue), so here is the full log: https://openqa.qubes-os.org/tests/23199/file/system_tests-tests-qubes.tests.extra.log
> 
> Example failures:
> 
> ```
> =====================================================================
> FAIL: splitgpg.tests/TC_00_Direct_debian-11/test_080_option_parser
> Check if split-gpg agrees with gpg about options parsing
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 367, in test_080_option_parser
>     splitgpg_needs_arg = self._check_if_options_takes_argument(
>   File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 348, in _check_if_options_takes_argument
>     self.fail(
> AssertionError: qubes-gpg-client --list-key have not complained about --garbage options: Abbreviated option ‘--list-key’ must be written as ‘--list-keys’
> 
> 
> ======================================================================
> FAIL: splitgpg.tests/TC_00_Direct_fedora-34/test_031_sign_verify_detached
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 161, in test_031_sign_verify_detached
>     self.assertIn('\ngpg: Good signature from', verification_result.decode())
> AssertionError: '\ngpg: Good signature from' not found in "IDs must not start with '-'\nEOF\n"
> 
> ======================================================================
> FAIL: splitgpg.tests/TC_00_Direct_fedora-34/test_050_sign_verify_files
> Test for --output option
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/splitgpg/tests.py", line 269, in test_050_sign_verify_files
>     self.assertEquals(decoded_msg.decode(), msg)
> AssertionError: '' != 'Test message'
> + Test message
> ```
> 
> The first one is because `--list-key` is a valid alias for the `--list-keys` option, not only abbreviation.

I will fix the first one, and will change the other code to not complain about a leading `-` if it is the only character in an option.  I will also add UTF-8 validity checks.

2021-10-08 16:32 UTC, marmarek requested changes
Besides the below, tests still fail with `qubes-gpg-client --list-sig have not complained about --garbage options: Abbreviated option ‘--list-sig’ must be written as ‘--list-sigs’`

2021-10-08 16:32 UTC, marmarek commented on src/gpg-common.c
> +                        "Abbreviated option ‘--%.*s’ must be written as ‘--%s’\n",
Please avoid using non-ASCII characters in the error messages.

2021-10-08 16:32 UTC, marmarek commented on src/gpg-common.c
> +                fprintf(stderr, u8"Non-option arguments must not start with ‘-’, unless preceeded by “--”\n"
Here too.

2021-11-08 17:42 UTC, marmarek commented
> The way I debugged this in the past was by changing the gpg-wrapper to echo all commands to a file,

I did the same here. And got this:
```
qubes-gpg-client-wrapper --enable-special-filenames --batch --no-sk-comments --status-fd 99 --no-tty --charset utf8 --enable-progress-filter --exit-on-status-write-error --display :0 --logger-fd 101 --sign --detach --armor --textmode -u 465649BEF6CF08B0 -- '-&102'
Abbreviated option '--detach' must be written as '--detach-sign'
```

2021-12-09 07:01 UTC, DemiMarie commented
PipelineRetry

2021-12-12 18:45 UTC, marmarek approved these changes

2021-12-12 18:46 UTC, merged