Prevent GPG from launching a photo viewer
QubesOS/qubes-app-linux-split-gpg pull request #68
Opened 2022-02-10 21:00 UTC by DemiMarie

Images in GPG keys can come from untrusted sources via
`qubes.GpgImportKey`.  Viewing them in the server is a large and
unnecessary attack surface and should not be allowed.  Programs that
access images via `--attribute-fd` are unaffected.
    
Tested manually; automated tests will be added later in the course of
adding unit tests to split-gpg.

2022-02-12 18:53 UTC, DemiMarie commented
PipelineRetry

2022-02-13 16:27 UTC, DemiMarie commented
PipelineRetry

2022-02-14 19:18 UTC, marmarek requested changes

2022-02-14 19:18 UTC, marmarek commented on src/gpg-server.c
> +    remote_argv[3] = "--photo-viewer=/usr/bin/true";
Please use `/bin/true`, not every system have merged /usr.

2022-02-14 19:39 UTC, merged